image: biqa.tmax.com/hyperdata20.5_rel/hyperdata20.5_front:20230427_562b0be6

https:
  enabled: true

proxy:
  bodysize: 1024m
  # minutes
  timeout: 1800

resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi

db:
  mountPath: /db
  persistentVolumeClaimName: tibero-pvc-db

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

customLogo:
  path: /usr/share/nginx/html/res/images/common/gnb

language: ko

legacy:
  #redirect to
  redirect: https://192.168.179.40:8080
