image: biqa.tmax.com/v20.5/hyperdata20.5_visualization:20230504_v1

version:
  major: 20

https:
  enabled: true

proxy:
  bodysize: 1024m
  # minutes
  timeout: 1800

server:
  ip: 192.1.1.249
  port: 30303
  servlet:
    contextPath: /hyperdata/v1
  home: /cnb
  do: /do
  share:
    host_url: "192.1.1.249"
    port: "30303"

download_max_row: -1

hyperdata_svc:
  virtualization:
    name:
      hyperdata-virtualization-svc
    port:
      8500
  system:
    name:
      hyperdata-system-svc
    port:
      8100


loadBalancer:
  enabled: true
  ip: 192.1.1.93

loggingPath: /db/visualization

db:
  address: tiberolocaldns
  port: 8629
  persistentVolumeClaimName: tibero-pvc-db
  mountPath: /db
  username: hyperdata
  password: tmax
  sid: tibero
  driver_class_name: com.tmax.tibero.jdbc.TbDriver
  jdbc_url: jdbc:tibero:thin:@tiberolocaldns:8629:tibero

resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi

spark:
  partition:
    shuffle_partition: 1
