imagePullPolicy: IfNotPresent
image: 192.168.179.44:5000/hyperdata20.4.0.6.0_flow:latest

server:
  port: 8081
  servlet:
    contextPath: /hyperdata20/flow

proxy:
  bodysize: 1024m
  timeout: 1800 # minutes

resources:
  requests:
    cpu: 2
    memory: 2Gi
  limits:
    cpu: 6
    memory: 4Gi

pvc:
  name: tibero-pvc-db
  mountPath: /db

logging:
  path: HyperData/logs/flow

svc:
  virtualization:
    name: hyperdata-virtualization-svc
    port: 8500
  management:
    name: hyperdata-system-svc
    port: 8100
  mlplatform:
    name: mlplatform-backend-svc
    port: 18081

hostAlias:
    ip: "192.168.220.220"
    hostname: "k8s-19-worker04"

db-connection-pool:
  common:
    query-timeout: 3600
    wait-timeout: 3600
  hyperdata:
    max-active: 30
    min-idle: 2
    max-idle: 2
    idle-timeout: 10
  hyperdata_ex:
    max-active: 30
    min-idle: 2
    max-idle: 2
    idle-timeout: 10
  hyperdata_editor:
    max-active: 4
    min-idle: 1
    max-idle: 1
    idle-timeout: 10

flow:
  save:
    max-file-row: 20000
sql-editor:
  preview-max-row: 1000

