image: 192.168.179.44:5000/hyperdata20.4_hd:20210820182035
version:
  major: 20

https:
  enabled: true

proxy:
  bodysize: 1024m
  # minutes
  timeout: 1800

webserver:
  ip: 192.168.99.100
  port: 31370

loadbalancer:
  enabled: true
  SUPERVDB_UCS_PORT: 9994
  
neo4j:
  ip: neo4j-hd-gdb:7687/bolt
  password: tmax
  username: neo4j

ssvr5:
  SSVR5_LISTENER_PORT:
  SSVR5_JAVA_AGENT_PORT:
  
db:
  address: tiberolocaldns
  persistentVolumeClaimName: tibero-pvc-db
  mountPath: /db

resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi
  
mlplatform:
  ip: mlplatform-backend-svc
  port: 18080

customLogo:
  enabled: false

customAddon:
  enabled: true
  url: https://www.tmaxsoft.com/blog/

sqlEditor:
  enabled: false
  web_studio_ip: null

dataCollection:
  enabled: false
