apiVersion: v1
kind: ConfigMap
metadata:
  name: hyperdata-flow-configmap
data:
  application.yml: |
    svc:
      virtualization:
        ip: {{ .Values.svc.virtualization.name }}
        port: {{ .Values.svc.virtualization.port }}
      management:
        ip: {{ .Values.svc.management.name }}
        port: {{ .Values.svc.management.port }}
      mlplatform:
        ip: {{ .Values.svc.mlplatform.name }}
        port: {{ .Values.svc.mlplatform.port }}

    ############################ Servlet Config ############################
    server:
      port: {{ .Values.server.port }}
      servlet:
        context-path: {{ .Values.server.servlet.contextPath }}

    ############################ Output Config ############################
    ws:
      filepath: {{ .Values.pvc.mountPath }}/input
      saveoutput_filepath: {{ .Values.pvc.mountPath }}/output
      saveoutput_temp_filepath: {{ .Values.pvc.mountPath }}/temp

    ############################ Connection Pool Config ############################
    db-connection-pool:
      common:
        driver-class-name: com.tmax.tibero.jdbc.TbDriver
        query-timeout: {{ index .Values "db-connection-pool" "common" "query-timeout" }}
        wait-timeout: {{ index .Values "db-connection-pool" "common" "wait-timeout" }}
      hyperdata:
        max-active: {{ index .Values "db-connection-pool" "hyperdata" "max-active" }}
        min-idle: {{ index .Values "db-connection-pool" "hyperdata" "min-idle" }}
        max-idle: {{ index .Values "db-connection-pool" "hyperdata" "max-idle" }}
        idle-timeout: {{ index .Values "db-connection-pool" "hyperdata" "idle-timeout" }}
      hyperdata_ex:
        max-active: {{ index .Values "db-connection-pool" "hyperdata_ex" "max-active" }}
        min-idle: {{ index .Values "db-connection-pool" "hyperdata_ex" "min-idle" }}
        max-idle: {{ index .Values "db-connection-pool" "hyperdata_ex" "max-idle" }}
        idle-timeout: {{ index .Values "db-connection-pool" "hyperdata_ex" "idle-timeout" }}
      hyperdata_editor:
        max-active: {{ index .Values "db-connection-pool" "hyperdata_editor" "max-active" }}
        min-idle: {{ index .Values "db-connection-pool" "hyperdata_editor" "min-idle" }}
        max-idle: {{ index .Values "db-connection-pool" "hyperdata_editor" "max-idle" }}
        idle-timeout: {{ index .Values "db-connection-pool" "hyperdata_editor" "idle-timeout" }}

    ############################ Flow Config ############################
    flow:
      save:
        max-file-row: {{ index .Values "flow" "save" "max-file-row" }}
