apiVersion: v1
kind: ConfigMap
metadata:
    name: hive-config
data:
    OM_KUBE_DNS: om
    OM_PORT: "9874"
    MYSQL_KUBE_DNS: mysql
    MYSQL_PORT: "3306"
    HIVE_META_DB: metastore
    HIVE_META_USER: root
    HIVE_META_VOLUME: hyperdata
    HIVE_META_BUCKET: hive
