apiVersion: v1
kind: Pod
metadata:
  labels:
    lb: {{ .Release.Name }}-db
  name: {{ .Release.Name }}-pod-db-hd
spec:
  hostname: tibero
  subdomain: {{ .Release.Name }}-svc-db
  containers:
  - env:
    - name: TB_PORT
      value: "8629"
    - name: MAX_SESSION_COUNT
      value: "40"
    - name: TOTAL_SHM_SIZE
      value: "2"
    - name: MEMORY_TARGET
      value: "4"
    - name: LOG_BUFFER
      value: "300M"
    - name: LOG_GROUP
      value: "5"
    - name: LOG_FILE_SIZE
      value: "200M"
    - name: SYSTEM_FILE_SIZE
      value: "1G"
    - name: TEMP_FILE_SIZE
      value: "5G"
    - name: UNDO_FILE_SIZE
      value: "1G"
    - name: USR_FILE_SIZE
      value: "5G"
    - name: DB_CHARACTER_SET
      value: "UTF8"
    image: {{ .Values.image }}
    name: {{ .Release.Name }}-con-db-hd
    ports:
    - containerPort: 8629
      name: tb-lsnr
      protocol: TCP
    - containerPort: 8630
      name: tb-sp
      protocol: TCP
    - containerPort: 9999
      name: ora-gw
      protocol: TCP
    - containerPort: 9095
      name: nz-gw
      protocol: TCP
    - containerPort: 9093
      name: iq-gw
      protocol: TCP
    - containerPort: 9094
      name: ase-gw
      protocol: TCP
    - containerPort: 9777
      name: my-gw
      protocol: TCP
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
        nvidia.com/gpu: "0"
      requests:
        cpu: "2"
        memory: 4Gi
        nvidia.com/gpu: "0"
    volumeMounts:
    - mountPath: /db
      name: pv-storage
    - name: tz-seoul
      mountPath: /etc/localtime
  securityContext:
    sysctls:
    - name: kernel.sem
      value: 10000 32000 10000 10000
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: {{ .Release.Name }}-pvc-db
  - name: tz-seoul
    hostPath:
      path: /usr/share/zoneinfo/Asia/Seoul

